### ISSUE TITLE
Write strings on the Dynamixel bus

### ISSUE THREAD

**Issue by JamesNewton** [HaddingtonDynamics/Dexter#32]
In order to support more complete IO via the Tinyscreen+ on the v2 Tool Interface, it would be very good to be able to send it strings of data instead of just 4 bytes at a time.

**Comment by cfry** [comment]
Would it be a good idea to be able to send such strings from DDE?
Mostly I suspect no, but this *could* be used to test the
connectivity to the tinyScreen.

Also, if the computer running DDE was remote from
the Dexter, its a way that a dde programmer could
communicate with the Dexter operator.

I'd guess we'd need a new oplet for this,
though perhaps a "set_parameter" to "tiny_screen_display" could work.

**Comment by JamesNewton** [comment]
It is set_parameter. See the documentation (just updated) at 
https://github.com/HaddingtonDynamics/Dexter/wiki/End-Effector-Screen
towards the bottom.

**Comment by cfry** [comment]
Great.
I tried way back when to be able to move a string from
DDE to become an arduino program and failed.
Maybe we can take another whack at it,
as it would be nice to just edit a file in DDE
then shove it into the TinyScreen.

Nice set of utility functions.
Let's talk about incorporating those into DDE.
We can put a "class" around them,
make a section of the Ref Man for them
and do a little language smithing.

I presume we'll want to figure out how
to get a button click back from the TinyScreen
which will be a challenge, but maybe we
can at least map out potentially desirable functionality
to give ourselves some guidelines.

**Comment by JamesNewton** [comment]
We have a dedicated return data line from the Tinyscreen+ to the FPGA, but no USART in the FPGA to read it yet. Thanks for the reminder, that's another issue. And we need to extend read_from_robot to read back FPGA data as well. @JamesWigglesworth and I just got a data (vs file) readback to work on that the other day, so it shouldn't be terribly hard. It's issue #11

**Comment by JamesNewton** [comment]
Implementation of Dynamixel communications was moved from the FGPA to DexRun.c. The `SendWrite1Packet` function needs to be updated to accept a char array rather than a single char.

**Comment by JamesNewton** [comment]
Kamino cloned this issue to [HaddingtonDynamics/OCADO](https://github.com/HaddingtonDynamics/OCADO/issues/32)
