### ISSUE TITLE
Update BOM spreadsheet

### ISSUE THREAD

**Issue by JamesNewton** [HaddingtonDynamics/Dexter#34]
https://docs.google.com/spreadsheets/d/1uk89q76vcK4OT9NTM6qxsPpkON_QM3-OrlhfjPigGuE

Bring up todate with kickstarter and HD tabs

**Comment by cfry** [comment]
I like this list of parts.
It helps me get a feel for just how complex a Dexter is.

If the comment:
"Bring up todate with kickstarter and HD tabs"
is a "do list item" for this spreadsheet,
I'd add to that
1. What is this a parts list for?
 The only title is
"NOTE: THIS SHEET NEEDS TO BE UPDATED AND MAY BE INCORRECT"

2. Date.

3. state explicitly that the "sidebar" of "Total Hardware " is redundant
with those same parts mentioned elsewhere (if that's the case).
I like having the "total hardware" but it doesn't add to the
total parts count if I understand it correctly.

4. make a total parts count for every one of the "sub-sub assemblies"
5. Make a total parts count for each subassembly.
6. Make a grand total parts count.
this will help us compare the complexity of different Dexter versions.
As I understand it, the HD Dexter has many fewer parts so
it would be nice to have a comparison of the progress that's
been made with the HD design.

**Comment by bmv437** [comment]
Have you considered using a PBS (Product Breakdown Structure) for the parts and assemblies?
Another very complex project I follow just posted a video about how a PBS changed the way they tackle the project:

https://www.youtube.com/watch?v=zVyEsMiwvVc

Here's their Blank PBS Template with analytics:
https://docs.google.com/spreadsheets/d/1eKW_-ygHTu2z4inSSGPFnjAoIolORW19d-Xu-uhDw9E/edit

**Comment by JamesNewton** [comment]
I certainly have! If I could find the time I would do it. If you have time, please help us?

**Comment by AndrewSmart** [comment]
PBS looks useful. I made an [attempt](https://docs.google.com/spreadsheets/d/1hJnaWNOxw2grD4kduyf22FARP7wVjzjn6f_6CNK4B-Y/edit?usp=sharing).

By script it makes a list of 3D parts, hardware, and their quantity from the main tab. Sorted alphabetically. Run the **populate_tabs** macro to update the tabs.

The main tab is ordered as it in OnShape, should make it easier to visually see future changes. Row groups and dashes in the names help show hierarchy (maybe whitespace would be better now that I think about it).

**Comment by JamesNewton** [comment]
Wow @AndrewSmart that rocks! Thank you! 

I hope you can help me understand it better?
1. it looks like the harmonic drives aren't included in the hardware tab. Apparently, that's because they aren't assigned a type. Looking at line 110 / 110 in the list shows the type set to nothing. Is correcting that just as easy as changing the type to H for hardware?

2. The "bottom section" and "second section" don't appear to have any detail in them. But those sections do have detail in them in OnShape. Was that part of the setup just not finished? I'd like to learn how to finish it if you have time for a call or other means of educating me. 

3. Is there a way of getting the default quantity to be 1 or some other way to total the e.g. number of ball bearings one needs? Looking at the Hardware tab there are a number of KP0056-01_SB6703ZZ_2_03 ball bearings, but no idea how many total you need to order. Is there a way of getting that information? I thought the Wintergatan PBS did that?

Again, thank you for this amazing effort, and I really hope we can work together to bring it to full use.

**Comment by JamesNewton** [comment]
Thanks Andrew! I'm understanding that we used Inventor initially, and are now switching to Fusion 360. More when @JamesWigglesworth is available, probably next week.

**Comment by JamesNewton** [comment]
Thanks Andrew! Couple of questions:
1. I can't expand the collapsed sections on the PBS tab. It says I'm trying to edit a protected cell or object. But I can change the status and other columns... 
2. On the hardware tab, some items are totaled and others are not, I'm trying to understand what triggers that or misses that. e.g. lines 25-27 should probably be totaled. I'm looking for the code that makes that choice but I don't see it. Did you just do that manually?

**Comment by AndrewSmart** [comment]
> 1. I can't expand the collapsed sections on the PBS tab. It says I'm trying to edit a protected cell or object. But I can change the status and other columns...

Ok strange, everything with the link can edit the entire document. I did protect column A from edits as that is autogenerated. I guess that prevented others from expanding the row groups, so I've removed that protection, must be a bug with Google Sheets.
Should work now.

> 2. On the hardware tab, some items are totaled and others are not, I'm trying to understand what triggers that or misses that. e.g. lines 25-27 should probably be totaled. I'm looking for the code that makes that choice but I don't see it. Did you just do that manually?

In grouping of the hardware tab right now the situation of the CAD ID being blank and the Name having a # suffix isn't handled as you point out.

Nope did not do it manually, grouping is done automatically on the BOM tabs. The code that does it is `function group_sheet`. It has a nested for loop, the outer loop goes from the bottom of the sheet to the top, the inner loop from there up as long as matches are found.

I'll try to fix that real quick.

**Comment by JamesNewton** [comment]
Andrew, that's excellent! It really looks quite nice now. 

Our lead mechanical engineer, @JamesWigglesworth, tells me that we are standardizing on Fusion 360 for new designs. Have you worked with that before? There are free (as in free to use, not open source) licenses for it that individuals can get for non-commercial work if you would like to try it. I assume the current process would be the same? Export the STEP files from Fusion, import into FreeCAD, run the macro, move the data into the sheet?

**Comment by AndrewSmart** [comment]
Thank you. Nope, I have not worked with Fusion 360.
> I assume the current process would be the same? Export the STEP files from Fusion, import into FreeCAD, run the macro, move the data into the sheet?

Correct. Reminds me, I ought to share this document/workflow with the [FreeCAD community](https://forum.freecadweb.org/viewtopic.php?f=8&t=23592&start=10).

**Comment by maxsu** [comment]
@JamesNewton, @AndrewSmart: 

1. What's the status on the PBS-BoM update?
2. What's the status on the Onshape to F360 migration? 
3. What's our current best thinking on unobtrusive PBS-style part/assembly numbering in F360?

@AndrewSmart, since F360 is freely available to potential collaborator and extensible /w python, I'd like to recommend we skip Freecad as a project dependency and go with F360. We can find or [develop](https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-9701BBA7-EC0E-4016-A9C8-964AA4838954) an [add-in](https://knowledge.autodesk.com/search-result/caas/sfdcarticles/sfdcarticles/How-to-install-an-ADD-IN-and-Script-in-Fusion-360.html) to update the BOM after substantive changes. Currently looking at your [Freecad Macro](https://github.com/AndrewSmart/ProductBreakdownStructure/blob/master/export_to_pbs_csv.FCMacro) - at first glance it will not be hard to port over (with the proviso that F360 has a similar assembly hierarchy.)

If we build the add-in from scratch, I'd like to reuse it in other F360-standardized open hardware projects (I'd like to use a similar PBS methodology for [StanfordDoggo](https://github.com/Nate711/StanfordDoggoProject)) - I think the existing macro's philosophy meets that requirement.

@AndrewSmart  can you share a quick example of the CSV output from your FCMacro? I'd like to document the existing PBS.csv format.

Tentative next steps here: 
1. Find or dev PBS.csv-compatible BoM add-in for F360
2. Locate Dexter F360 model; Add @AndrewSmart's PBS numbering
3. Integrate BoM add-in; draft updated BoM contributor workflow

**Comment by AndrewSmart** [comment]
> @AndrewSmart can you share a quick example of the CSV output from your FCMacro? I'd like to document the existing PBS.csv format.

@maxsu It's in the last tab of the [google sheet](https://docs.google.com/spreadsheets/d/1hJnaWNOxw2grD4kduyf22FARP7wVjzjn6f_6CNK4B-Y/edit?usp=sharing) I made. I just imported the CSV into that tab, then... I think I manually copied over the columns to the PBS tab, I don't recall if that was scripted. More scripting would need to be done to automate updates, e.g. propagating parts added/removed from CAD model to the PBS document, handling conflicts or whatever (e.g. strikethrough of deprecated parts). I didn't think the scripting worth the effort if HD wasn't going to use it, but what I did met my needs so I didn't do more.
Yes I changed the PBS numbering a bit to handle the hierarchy depth.

**Comment by jonfurniss** [comment]
@maxsu We are currently on the tail end of finishing up the Fusion 360 port and assembly. To be able to more easily edit parts in the future, we redrew everything from scratch in Fusion. We are internally going through to test everything out and make sure it's correct, so we're not quite ready to share it publicly yet. 
We started using the PBS numbering system for our part numbers, which we have put as a prefix on each part as we redrew them, which I assume will make the scripting process work easier.
We definitely welcome any help for automatically extracting a PBS BOM from Fusion 360 with an add-in or Python script.

**Comment by JamesNewton** [comment]
Kamino cloned this issue to [HaddingtonDynamics/OCADO](https://github.com/HaddingtonDynamics/OCADO/issues/34)
