### ISSUE TITLE
Startup / Home Dexter in Positions other than Straight up

### ISSUE THREAD

**Issue by JamesNewton** [HaddingtonDynamics/Dexter#35]
In some applications, it is not possible to have Dexter setup in a completely straight or vertical position. It would be good to be able to start Dexter in an offset position.

**Comment by cfry** [comment]
I am expecting most jobs to assume Dexter could be
in any position at startup and thus they
should move dexter to a "starting position" before
doing the domain-specific activity of the job.
Do to tool paths and things that "might be in the way",
this might mean moving dexter twice,
ie once "straight up" as far as it can go"
then, now that its theoretically clear of the workspace,
over to a high "x, y start position".
Then from THERE we start the job's specific movements
in earnest.

One trick to normally avoid obstacles is
before moving TO somewhere on the work surface,
first move up to a neutral high position.
This won't always work, but is a good heuristic.

**Comment by JamesNewton** [comment]
b5c8c9815294405c8ec51c3ce6bdb3ed3433e139 is an effective workaround for this but it will not work if you are using DDE to do kinematics. (e.g. Dexter.move_to )

**Comment by JamesNewton** [comment]
Kamino cloned this issue to [HaddingtonDynamics/OCADO](https://github.com/HaddingtonDynamics/OCADO/issues/35)
