### ISSUE TITLE
Dexter.move_to_relative does not function in simulator mode.

### ISSUE THREAD

**Issue by tasashlar** [HaddingtonDynamics/Dexter#41]
DDE 2.4.3 osx 10.12.6

Team,

I was doing some pre-emptive dev work before receiving my dexter and the function:

dexter.move_to _relative does not appear to work on the sim.

When executing the following code based on the doc

new Job({name: "test_job",
         do_list: [Dexter.move_all_joints(Dexter.NEUTRAL_ANGLES),
                   Dexter.move_to_relative([0.005, 0.01, 0]),
                   Dexter.move_to([0.1, 0.1, 0.1])
                   ]})
The sim does not reflective any movement at all. All lines after the move_to_relative in the job also fail.
If you comment out the move_to_relative it all appears to work as expected.

Is this because the function needs position data from the robot and the sim does not emulate it it fully?
Other Ideas?

Thanks

**Comment by cfry** [comment]
Thanks for the bug report.
I am running a very new release of DDE and I have been tweaking the
move commands so its *possible* that I fixed a bug I didn't know we had!
But another possibility is that you commanded Dexter to move out of range.
You didn't give say if there were any error messages, but
its normal that when moving to some random x, y z location, it will
be out of range. This will cause the job to error.
The Job's button will turn red and there will be a tooltip on the button with
an error message. For out of range problems you should also see
some red test error message in output pane.
When I run your code on my latest DDE version the job runs to completion without
erroring, but it doesn't *look* like it makes all the moves it should.
new Job({name: "test_job",
	do_list: [Dexter.move_all_joints([0, 30, 30, 30, 30]),
				Dexter.move_to_relative([0.05, 0.01, 0.01]),
			  Dexter.move_to([0.1, 0.1, 0.1])
]})
is a job that makes the relative move more obvious,
but you still have to look carefully at the simulation.

Playing with DDE simulator before getting your dexter is indeed a good thing 
to do before getting your Dexter. 
I encourage you to click on the big blue ? in the upper right
of the doc pane to see how to get help within DDE.

Once we have a few days experience with my new release,
and it checks out ok, I'll make it public.

**Comment by JamesNewton** [comment]
Kamino cloned this issue to [HaddingtonDynamics/OCADO](https://github.com/HaddingtonDynamics/OCADO/issues/41)
