### ISSUE TITLE
txt.string_to_lines fails with 1 char string

### ISSUE THREAD

**Issue by cfry** [HaddingtonDynamics/Dexter#46]
This function creates the dxf for drawing a string.
it works for 2 + lengthed strings but not for 1 char strings.
This is a useful function so let Fry know when its fixed
so I can document it.

**Comment by JamesNewton** [comment]
To clarify, this is a DDE issue, correct?

**Comment by JamesWigglesworth** [comment]
Fixed:
https://github.com/cfry/dde/commit/f4e3ba369fb5c9e285b7836f41795a8c86ecdc8d#diff-0e6dc4fac949e204d6599e0290535e64

Will be in DDE v3.0.8 and later.

**Comment by JamesNewton** [comment]
Kamino cloned this issue to [HaddingtonDynamics/OCADO](https://github.com/HaddingtonDynamics/OCADO/issues/46)
