### ISSUE TITLE
Link Length Diagram

### ISSUE THREAD

**Issue by JamesWigglesworth** [HaddingtonDynamics/Dexter#49]
Need a diagram showing where the link lengths are measured from.
Currently there is only one showing L4 and L5 in DDE.

**Comment by cfry** [comment]
The link length of a link should be the distance
between the pivot points of the
surrounding joints for a link, right?

**Comment by JamesNewton** [comment]
This is the one that shows L4 / L5 correct:
https://github.com/cfry/dde/blob/master/doc/coor_images/Tooltip_Location.PNG

**Comment by JamesNewton** [comment]
Kamino cloned this issue to [HaddingtonDynamics/OCADO](https://github.com/HaddingtonDynamics/OCADO/issues/49)

**Comment by JamesNewton** [comment]
See Kinematics page in wiki
