### ISSUE TITLE
'Left' configs no longer work

### ISSUE THREAD

**Issue by JamesWigglesworth** [HaddingtonDynamics/Dexter#53]
Joint 5 appears to be off by 180° in left configs.
Other configs may not be working either. 
Mostly likely broken in both DDE and DexRun inverse kinematics.

**Comment by cfry** [comment]
IS this something that happened in the latest DDE release,
or has it been there for a while?

**Comment by JamesWigglesworth** [comment]
I think it's been in there for a while.My guess is ever since we had the confusion over which rotation direction was positive.

Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by JamesWigglesworth** [comment]
Bug fixed.
Will be in DDE release 3.0.8 and later.

To test here's position and direction that work with all combinations of configs:
[0, 0.3, 0.4], [0, 0, -1]

**Comment by JamesNewton** [comment]
Kamino cloned this issue to [HaddingtonDynamics/OCADO](https://github.com/HaddingtonDynamics/OCADO/issues/54)
