### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by JamesNewton** [HaddingtonDynamics/Dexter#65]
Just a fake issue to make it easy to add pictures to the Wiki.

**Comment by JamesNewton** [comment]
![GripperTickMarkPositionToLoadTool_1](https://user-images.githubusercontent.com/419392/57670424-18b3ff00-75c4-11e9-9521-967dbbd6b59b.JPG)
![GripperTickMarkPositionToLoadFinger_1](https://user-images.githubusercontent.com/419392/57670426-1baeef80-75c4-11e9-8f35-2c820016c5ce.JPG)

**Comment by JamesNewton** [comment]
![DexterFPGA_Overview](https://user-images.githubusercontent.com/419392/57746151-be2ea780-7684-11e9-80b5-95490f015973.png)

**Comment by Kenny2github** [comment]
Transparent
![icon](https://user-images.githubusercontent.com/28599280/57841521-489a1700-77fd-11e9-959b-8defaa382436.png)

**Comment by JamesNewton** [comment]
![image](https://user-images.githubusercontent.com/419392/58519674-779f7980-8169-11e9-9146-c67a6d174f35.png)

**Comment by JamesNewton** [comment]
Picture of clamping Dexter base to a table

![image](https://user-images.githubusercontent.com/419392/58844223-183edf00-862b-11e9-8197-37fc97029a21.png)

**Comment by JamesNewton** [comment]
Screwing a Dexter to the table
![image](https://user-images.githubusercontent.com/419392/58844593-c5febd80-862c-11e9-9076-bd438fcaf95d.png)

**Comment by JamesNewton** [comment]
Hot gluing Dexter to a table
![image](https://user-images.githubusercontent.com/419392/58844667-183fde80-862d-11e9-8bcc-aeaed5865306.png)

**Comment by cfry** [comment]
Crystal clear picture of screwing!
For the hot glue, how about a picture with
one hole filled with glue and the glue gun poised to
squirt in glue to the 2nd (as yet unfilled).
It would be really good if the color of the glue
was not the same color as a foot.

Most pictures in most "assembly manuals"
are so low res as to be pretty ambiguous as
to what you really need to do.
This aren't!

**Comment by JamesNewton** [comment]
Hotglue in a foot
![image](https://user-images.githubusercontent.com/419392/58922776-4dae0000-86f1-11e9-9b93-85de3b98551f.png)

**Comment by cfry** [comment]
In the screwing picture, there are only 2 holes in a foot.
Here it looks like there's 4, but in any case
this new black and white picture is confusing,
much more so than the color screwing picture.

**Comment by jonfurniss** [comment]
There are two holes for screwing into on the top of the robot foot.
There are four indents underneath the foot that can be filled with glue to
use for additional traction.
While the two holes for screwing line up with the front two glue indents,
the two features are for different purposes and not related.

**Comment by cfry** [comment]
Thanks. Now the challenge is to take a picture that
let's you know you're even looking at the bottom of a foot.
Also, I am guessing that you have to
dab glue onto 2 or 3 feet at once then
plunk the whole robot firmly on the table.

**Comment by JamesNewton** [comment]
Image of shipping case with first layer / base
![image](https://user-images.githubusercontent.com/419392/59459216-1c0ff580-8dd1-11e9-8ece-7ac85a8863e8.png)

**Comment by JamesNewton** [comment]
Where to grab Dexter out of the packing case.
![image](https://user-images.githubusercontent.com/419392/59470338-36a39800-8dec-11e9-8b33-f0f3ae1827b8.png)

**Comment by JamesNewton** [comment]
Correct jumper settings on MicroZed board
![image](https://user-images.githubusercontent.com/419392/59471887-65703d00-8df1-11e9-8719-f88cfd6d3ffb.png)

**Comment by JamesNewton** [comment]
Bad encoder eye. LED pulled out of encoder block.
![image](https://user-images.githubusercontent.com/419392/59715702-4f83c300-91c9-11e9-85df-87ec6569a9de.png)

**Comment by JamesNewton** [comment]
Good encoder, after replacing LED in hole of encoder block.
![image](https://user-images.githubusercontent.com/419392/59716213-6d9df300-91ca-11e9-87d6-0b530f39fb61.png)

**Comment by JamesNewton** [comment]
LED or Photo sensor pulled out of hole in encoder block
![image](https://user-images.githubusercontent.com/419392/59716415-cff6f380-91ca-11e9-94e7-980a95b79e56.png)

**Comment by cfry** [comment]
It seems to me that the main hardware problems with Dexter are
with the encoders and their optical sensors, is that right?

**Comment by JamesNewton** [comment]
This is what you should see on the console after installing a WiFi adapter. Note that it does not have an IP address, but it is shown in the list of adapters, after eth0 and lo. 
![image](https://user-images.githubusercontent.com/419392/67534526-56dd4080-f683-11e9-87b8-1a84c22a2c8d.png)

**Comment by JamesNewton** [comment]
Opening screen of `nmtui`
![image](https://user-images.githubusercontent.com/419392/67534650-f39fde00-f683-11e9-8946-5ddc322f6b61.png)

**Comment by JamesNewton** [comment]
Select Activate a connection in `nmtui`
![image](https://user-images.githubusercontent.com/419392/67534741-64df9100-f684-11e9-8679-df477c2321a2.png)

**Comment by JamesNewton** [comment]
Selecting an SSID in `nmtui`
![image](https://user-images.githubusercontent.com/419392/67534796-acfeb380-f684-11e9-81fc-42a530e2b3dd.png)

**Comment by JamesNewton** [comment]
`ifconfig` now shows an IP address for the WiFi adapter.
![image](https://user-images.githubusercontent.com/419392/67534884-0e268700-f685-11e9-9cb1-673706d8b68b.png)

**Comment by JamesNewton** [comment]
Correct orientation for insertion / removal of tools from the Version 2 Tool Changer. 
![image](https://user-images.githubusercontent.com/419392/69197573-a67a2500-0ae6-11ea-937c-cc6d421945ed.png)

**Comment by JamesNewton** [comment]
Re-inserting the SD Card. SEE:
https://github.com/HaddingtonDynamics/Dexter/wiki/SD-Card-Image
for critical instructions!

![image](https://user-images.githubusercontent.com/419392/77209850-a736be00-6abc-11ea-9a6d-8ea40118f6dd.png)

**Comment by JamesNewton** [comment]
Dexter HDI packedin case:
![IMG_20200601_145504](https://user-images.githubusercontent.com/419392/83582222-cd81cc80-a4f5-11ea-9bb1-2243b52d74b4.jpg)

**Comment by JamesNewton** [comment]
Dexter HDI, removal from packing case
![delme](https://user-images.githubusercontent.com/419392/83825012-ea9cd380-a68c-11ea-8ad5-af9ef6979c80.jpg)

**Comment by JamesNewton** [comment]
Alignment mark on J1 on Dexter HDI
![J1align](https://user-images.githubusercontent.com/419392/83826349-8845d200-a690-11ea-8bba-e899748f2fb3.jpg)

**Comment by JamesNewton** [comment]
Dexter HDI with skin showing expected blue light.
![delme3](https://user-images.githubusercontent.com/419392/83826550-0609dd80-a691-11ea-8210-35bf60e937d9.jpg)

**Comment by JamesNewton** [comment]
Dexter FPGA control system block diagram.
![DexterFullControlSystem](https://user-images.githubusercontent.com/419392/88705673-b827b980-d0c4-11ea-9a36-98ca23db1be0.PNG)

**Comment by JamesNewton** [comment]
Dexter Control System, "Keep Position" section expanded. Note that integration is provided by the stepper motor /after/ the PID section. 
![DexterKeepMode](https://user-images.githubusercontent.com/419392/88705907-03da6300-d0c5-11ea-9963-557346285f53.PNG)

**Comment by JamesWigglesworth** [comment]
![CoM_Diagram](https://user-images.githubusercontent.com/26582517/91360228-e0c9ce80-e7aa-11ea-9465-29e0f4eb875d.PNG)

**Comment by JamesNewton** [comment]
Animation of one encoder sensor as the slot passes the mask.
![DexterEyeAnimation](https://user-images.githubusercontent.com/419392/93278868-a6849900-f77a-11ea-94a1-3a8694d31c93.gif)

**Comment by JamesNewton** [comment]
Animation of the encoder showing the phase between the two sensors. 
![DexterEncoderAnimation](https://user-images.githubusercontent.com/419392/93278905-c025e080-f77a-11ea-936e-0685ca073cac.gif)

**Comment by JamesNewton** [comment]
Diagram of link lengths 4 and 5

![image](https://user-images.githubusercontent.com/419392/94041118-a9851800-fd7e-11ea-8a59-1c177d40a7a9.png)

**Comment by JamesNewton** [comment]
![Dexter Motion Envelope - Top View](https://user-images.githubusercontent.com/419392/96189198-e911d080-0ef4-11eb-868c-c63a0f8b30f6.png)

**Comment by JamesNewton** [comment]
![Dexter HDI Motion Envelope - Side View](https://user-images.githubusercontent.com/419392/96189880-30e52780-0ef6-11eb-8ffd-4e77d4b6e493.png)

**Comment by JamesNewton** [comment]
Dexter HDI Joints Range Of Motion
![Dexter HDI Joints Range Of Motion](https://user-images.githubusercontent.com/419392/96190203-b1a42380-0ef6-11eb-92c3-84d30b67d975.png)

**Comment by JamesNewton** [comment]
![image](https://user-images.githubusercontent.com/419392/110830058-ab1f9b00-824d-11eb-9d89-7f9c11e9b0e4.png)

**Comment by JamesNewton** [comment]
![Drive spring, Position Correction, Torque sensing](https://user-images.githubusercontent.com/419392/135690468-7ba68ab5-bbc2-48b3-a0d0-bc06b26b48a9.png)
![Drive spring, Position Correction, Torque sensing Animation](https://user-images.githubusercontent.com/419392/135690566-5cc40a34-37d8-426e-a236-6dbd7dbe2b6b.gif)
