### ISSUE TITLE
Not able to interface the dexter arm with my PC having ubuntu 18.04

### ISSUE THREAD

**Issue by sumr4693** [HaddingtonDynamics/Dexter#81]
Hi,

I have not worked related to ethernet devices before, and so I have difficulties in interfacing my PC with the Dexter robot arm. I followed the instructions given in the website:

1. I set my ethernet adapter IP address to : 192.168.1.100 (for example) and subnet mask: 255.255.255.0
2. I connected the CAT 6a (tried also with new CAT 5e cable as well)  ethernet cable, which I found in the robot arm kit, between PC and dexter arm.
3. I tried to ping the dexter arm (whose default address is supposed to be 192.168.1.142) from both the command terminal and DDE interface. But I didn't get any response.
4. I tried the above steps for IP address for '0-255 in the last section for both 192.168.1.* and 192.168.0.* (after I kept my PC IP as 192.168.0.100) as well. But no response again.
5. I also tried by reinserting the mounted SD card in the board, and by switching off my WiFi when pinging the arm. But nothing worked.

Is there someway I can find the dexter ip address either from the physical connection, or by using and reading from the SD card? Please help me to fix this.

Thanks in advance!

**Comment by JamesNewton** [comment]
Please try the USB connection as per:
https://github.com/HaddingtonDynamics/Dexter/wiki/Dexter-USB-Connection
that will work IF the redboard is booting. Also check the troubleshooting page on the wiki to verify you are getting the expected lights on the board when it boots.

**Comment by sumr4693** [comment]
Thank you very much for your immediate response! Ok I will try these and let you know.

**Comment by sumr4693** [comment]
I made the USB connection between dexter and PC, and got the following boot commands from the dexter:

![Screenshot from 2020-05-18 14-04-45](https://user-images.githubusercontent.com/57145926/82211215-cd3bdb80-9910-11ea-959a-22878bfd9558.png)
![Screenshot from 2020-05-18 13-57-15](https://user-images.githubusercontent.com/57145926/82211281-e775b980-9910-11ea-87dd-49db431c6d88.png)
![Screenshot from 2020-05-18 13-57-47](https://user-images.githubusercontent.com/57145926/82211279-e6dd2300-9910-11ea-83b0-f7356e28cef3.png)
![Screenshot from 2020-05-18 13-58-24](https://user-images.githubusercontent.com/57145926/82211276-e6448c80-9910-11ea-8326-3b94608f7856.png)
![Screenshot from 2020-05-18 13-58-49](https://user-images.githubusercontent.com/57145926/82211272-e5abf600-9910-11ea-8e9b-589292c1147b.png)
![Screenshot from 2020-05-18 13-59-09](https://user-images.githubusercontent.com/57145926/82211268-e5135f80-9910-11ea-8f9e-9423d0564377.png)
![Screenshot from 2020-05-18 13-59-42](https://user-images.githubusercontent.com/57145926/82211265-e3e23280-9910-11ea-87a2-4af0f4cfa37f.png)
![Screenshot from 2020-05-18 14-00-03](https://user-images.githubusercontent.com/57145926/82211263-e3499c00-9910-11ea-83b4-a6f014f5899e.png)

From this info, will I be able to find anything useful to figure out the ethernet communication issue? Thanks in advance!

**Comment by sumr4693** [comment]
Also, I checked the LEDs status when booting:
Green: steady 'ON' (Power LED)
Blue: steady 'ON' (related to FPGA)
Red: 'ON' for few seconds and then 'OFF' (related to disk access to SD card)

Is Red LED functioning a normal behaviour?

**Comment by sumr4693** [comment]
Regarding the jumper configuration:

To boot from SD card, I saw that the jumpers should have the connections JP1: 1-2, JP2: 2-3, JP3: 2-3

And this is the image with the jumper connections:
![dexter_jumpers](https://user-images.githubusercontent.com/57145926/82212274-936bd480-9912-11ea-9909-4a3a727beda8.jpg)

The markings JP1, JP2 and JP3 in the microzed board seen above, are on the different locations from the board which is seen in Troubleshooting page. And I could see "1" on either sides of the three pins for each jumper, so it's confusing to locate the first pin for each jumper. I hope that the board in the attached image is the revised version.

Kindly clarify how to locate the numbers 1,2,3 for each jumper.

Thank you!

**Comment by JamesNewton** [comment]
Now I'm confused. I'm not aware of any changes to the labeling on the microzed board. Can you post a picture of your board showing that area? I'm checking with the group to see if they are aware of a change... what name did you order the kit under?

**Comment by JamesNewton** [comment]
In any case, based on your prior post of the USB data, it appears the jumpers are in the correct location, but the SD card isn't working correctly. e.g. it can't mount the ext partition and start the OS. It IS able to read the FAT partition and start the .bit file. I would re-burn the SD card from the image or contact sales for a replacement.

**Comment by sumr4693** [comment]
Thanks for figuring out the issue! I connected the SD card via card reader to my PC, and I am seeing a 16 GB volume drive (the list of files: boot.bin, devicetree.dtb, DexRun.c, uImage, xillydemo.bit and a folder - System Volume Information) and a 8 GB volume drive (I think this may be the ext partition)  
1. I don't find the details from the "SD card image" page on what the image file does look like. I will be using Etcher to flash the image, since my PC is Ubuntu based. Does Etcher automatically take care of the ext partition in the SD card? Is it just enough to add the flash file and select "Flash"? Or do I need to delete the contents or format the SD card?
2. In the "SD card image" page, it is mentioned to contact you to get the image file. Can you please provide the image file? 

This is the 16 GB volume drive screenshot:
![16_GB_vol](https://user-images.githubusercontent.com/57145926/82337039-95559680-99eb-11ea-96cd-725d39ee3b17.png)
This is the 8 GB volume drive screenshot:
![8GB_vol](https://user-images.githubusercontent.com/57145926/82337071-a30b1c00-99eb-11ea-8c79-f862cf169feb.png)

If this reburning doesn't work either, my company supervisor will be contacting sales team of Haddington Dynamics.

Thank you!

**Comment by sumr4693** [comment]
This is the microzed board image from the troubleshooting page:
![troubleshooting_page_microzed](https://user-images.githubusercontent.com/57145926/82337878-8cb19000-99ec-11ea-9d27-ccb368042c84.png)
And this is the microzed board I have in the robot arm:
![my_microzed](https://user-images.githubusercontent.com/57145926/82338221-ed40cd00-99ec-11ea-9c0b-202997cc7d64.png)

If you see both the images, the markings of JP1, JP2, JP3 are on the opposite sides. So I was wondering if there is any chance that the numbers 1,2,3 could also be reversed.

And, for your information, this robot arm was exported on May 9, 2019 from Haddington Dynamics. I am just a master thesis student, so I don't know regarding the order details. But the invoice has "Industrial Robots, NESOI" under description. Does this help?

Thanks!

**Comment by JamesNewton** [comment]
Can you email jamesnewton@hdrobotic.com so we can email you a link to the SD card image? And also, in the email please include what institution you are with and who your supervisor is so we can look this up in the sales db and provide appropriate support? Thank you. I will close this issue and we can continue support via email. I'm assuming something was damaged on the SD and it should be replaced rather than just re-imaged, but we can try that first.

**Comment by sumr4693** [comment]
Sure! I will contact you. Thank you for providing the email id!
